FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=vaultress/vaultress
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY vaultress.tar.gz /vaultress.tar.gz
RUN tar -xvf /vaultress.tar.gz

#ADD . /vaultress
RUN cd /vaultress/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /vaultress && scripts/windows-crosscompile/compile-vaultress.sh
